### ISSUE TITLE
Change figure size in pdf output

### ISSUE THREAD

**Issue by lazarusA** [rikhuijzer/Books.jl#192]
The current implementation outputs figures into the pdf document using the full width's page.  Which uses a lot of space and most times is not convenient. It will be nice to have an option where the size could be specified as a percentage or `in`(`cm`) width for given images.

**Comment by rikhuijzer** [comment]
Could you give an example where it is extremely problematic; out of curiousity.

But this sounds like a good idea, indeed :+1:

**Comment by lazarusA** [comment]
Ahh, basically you could start with the first plot [here](https://juliadatascience.io/juliadatascience.pdf) for CairoMakie, and similarly for the rest. It taking half a page, which is way too much.

**Comment by rikhuijzer** [comment]
The link refers to the document in general. Which section or page do you mean?

**Comment by lazarusA** [comment]
7.1 CairoMakie.jl, page 106.

**Comment by rikhuijzer** [comment]
Oh yes. Wow. That's not good:

![image](https://user-images.githubusercontent.com/20724914/131376681-7452670a-1aee-4f1d-8f4a-fc85be8486f8.png)

**Comment by rikhuijzer** [comment]
Note to self: let users pass `link_attributes` to Pandoc (https://pandoc.org/MANUAL.html#extension-link_attributes):

```
![](file.jpg){ width=50% }
```

will be converted to:

> - HTML: `<img href="file.jpg" style="width: 50%;" />`
> - LaTeX: `\includegraphics[width=0.5\textwidth,height=\textheight]{file.jpg}` (If you’re using a custom template, you need to configure graphicx as in the default template.)
> - ConTeXt: `\externalfigure[file.jpg][width=0.5\textwidth]`
