### ISSUE TITLE
Losing caption and label when creating a plot as M.myplot()

### ISSUE THREAD

**Issue by dmbates** [rikhuijzer/Books.jl#208]
First, thanks for writing and maintaining the package.

My coauthors and I have started converting a book about mixed-effects models using MixedModels.jl from another production system to Books.jl

Many of the plots that we use are somewhat complicated to construct and we would prefer not to divert the reader by the code as a block in the book.  Instead we prefer to show and discuss the plot then refer the reader to a later section where we discuss some principles of creating the figure.

I have seen two ways in the documentation and in the JuliaDataScience book for creating a figure.  The documentation suggests creating a function in the module and just calling that function in a jl code block.  I have tried that with a function like
```jl
function myplot(n::Integer)
    CairoMakie.activate!()
    fig, ax, plt = scatterlines(1:n, cumsum(randn(n)))
    ax.xlabel = "Index"
    ax.ylabel = "Cumulative deviations"
    filename = "random_walk"
    caption = "A random walk"
    label = "rndmwlk"
    Options(fig; filename, caption, label)
end
```
If I include the equivalent of `M.myplot(100)` (my module is named `EU`) in a jl code chunk, it produces a file `_gen/M_myplot_100.md` with contents
```md
![A random walk](_build/im/EU_myplot_100_.png){#fig:rndmwlk}
```
so it has taken the caption but used it as the alternate text for the figure.  Also it has constructed the label but there seems to be difficulty in referencing it in the text.  Furthermore, it seem to have ignored the filename from the `Options` call.

The html file for the section contains
```html
<img src="/im/EU_myplot_100_.svg" id="fig:rndmwlk" alt="A random walk" />
```

What I saw in the JDS book was putting the code from the body of the function in a string, say `s`, possibly with `# hide` annotations to remove boilerplate from the output.  It would look like
```jl
s = """
CairoMakie.activate!()                 # hide
fig, ax, plt = scatterlines(1:100, cumsum(randn(100)))
ax.xlabel = "Index"                    # hide
ax.ylabel = "Cumulative deviations"    # hide
filename = "random_walk"               # hide
caption = "A random walk"              # hide
label = "rndmwlk"                      # hide
Options(fig; filename, caption, label) #hide
"""
sco(s)
```

For this the html file contains
```html
<pre class="language-julia"><code>fig, ax, plt = scatterlines(1:100, cumsum(randn(100)))</code></pre>
<figure>
<img src="/im/random_walk.svg" id="fig:rndmwlk" alt="Figure 1: A random walk" /><figcaption aria-hidden="true">Figure 1: A random walk</figcaption>
</figure>
```

Ideally I would like to use a function to wrap the code (i.e. the first approach) so that I don't pollute the namespace in which the code is executing.  Also, I would prefer to have the option to suppress the printing of the code chunk.

Could you point me to where I would start looking to
- use a function like `myplot` to wrap the construction of the figure, returning an `Options` object
- have the filename, caption and label from the `Options` object used in the html
- suppress the printing of the source code and just display the figure

**Comment by rikhuijzer** [comment]
Thank you for your interest. I'm happy to hear that you're interested in making a Julia book. You seem to know exactly what you're doing. My compliments and are hitting things in my implementation that I'm not so proud of in terms of how correct it is.

How about a call? I think that is the most effective way for us to figure out a solution to your problems. I cannot find personal contact details of you, could you send me a mail at <t.h.huijzer@rug.nl>?

Otherwise, we can of course discuss things here. To start with

> Many of the plots that we use are somewhat complicated to construct and we would prefer not to divert the reader by the code as a block in the book. Instead we prefer to show and discuss the plot then refer the reader to a later section where we discuss some principles of creating the figure.

How about something like the following. In each block, I've put the filename of where the code snippet is located as a comment on the first line:

```
# src/plots.jl
function my_plot()
     fig = ...
     label = "myplot"
     return Options(fig; label, ...)
end
```

    # contents/my_content.md
    
    This statistical technique results in something like depicted in @fig:myplot.

    ```jl
    my_plot() # Here, we only show the figure.
    ```
    [...]
    @fig:myplot was created as follows:
    ```jl
    @sc my_plot()
    ```

**Comment by rikhuijzer** [comment]
Found another cause for the issues. In JuliaDataScience and Books.jl, we're always using newlines around `jl` code blocks. So, instead of

    lorem
    ```jl
    f()
    ```
    ipsum

we write

    lorem

    ```jl
    f()
    ```

    ipsum

Without the newlines, caption and label annotations aren't parsed by https://lierdakil.github.io/pandoc-crossref/.

I'll open a PR at your project to fix this.

**Comment by rikhuijzer** [comment]
This is resolved if I'm not mistaken. Feel free to re-open if there is still a problem.
