### ISSUE TITLE
suggesting font review for code blocks

### ISSUE THREAD

**Issue by epogrebnyak** [rikhuijzer/Books.jl#227]
Great package with big future I hope! Thanks  for maintainng it.

Noticed on Firefox the code blocks are in serif and not monospaced, maybe some chaneg in CSS can fix:

![изображение](https://user-images.githubusercontent.com/9265326/134813858-31420c87-7a08-47c9-9112-776386daec60.png)

**Comment by rikhuijzer** [comment]
This is an issue since the 2nd of July and I forgot about how it affects the font! https://github.com/rikhuijzer/Books.jl/issues/141#issuecomment-873467490.

Thank you very much for reporting this. I didn't notice it for months, because JuliaMono automatically works on my computer.

**Comment by rikhuijzer** [comment]
This is now sort of fixed. I changed the docs hosting to https://books.huijzer.xyz/about. I'll fix the underlying issue somewhere in the future. It's not really a priority for me right now.

Thanks again for letting me know about this issue.
