### ISSUE TITLE
The link to Books.pdf is missing

### ISSUE THREAD

**Issue by findmyway** [rikhuijzer/Books.jl#45]
The link to https://books.huijzer.xyz/books.pdf  in https://books.huijzer.xyz/ leads to 404 error.

**Comment by rikhuijzer** [comment]
Thanks for reporting it. This might take a while to be fixed, because it due to a missing texlive dependency. If you have the dependencies locally, then the build should pass.

**Comment by rikhuijzer** [comment]
The PDF should be available again in about 10 minutes :partying_face:.
