### ISSUE TITLE
Allow prefix for all links

### ISSUE THREAD

**Issue by rikhuijzer** [rikhuijzer/Books.jl#49]
Then, users can also host the book while using the GitHub or GitLab Pages domains instead of their own.

**Comment by findmyway** [comment]
Is there any progress on this?

**Comment by rikhuijzer** [comment]
> Is there any progress on this?

Sorry, I had some priorities for the PhD project coming up and also had some repetitive strain injury, so have tried to minimize programming. Anyway, it should be fixed now. Let me know if it doesn't work out. I'll register a new version in a few minutes.

**Comment by findmyway** [comment]
Great thanks. This project is really awesome! Take care and best wishes to your PhD project.

**Comment by rikhuijzer** [comment]
Thank you! Best wishes for you too. I'm really curious how your book is gonna look :smile:
