### ISSUE TITLE
Footnotes show up at references

### ISSUE THREAD

**Issue by rikhuijzer** [rikhuijzer/Books.jl#6]

**Comment by storopoli** [comment]
Right now (in main) the footnotes shows up if you create a `references.md` file and add it to the `contents` array in `config.toml`. See pic below:

<img width="657" alt="Screen Shot 2021-06-20 at 07 56 06" src="https://user-images.githubusercontent.com/43353831/122671448-fcb8b980-d19c-11eb-97ce-4ef0ffcc08dc.png">
