### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by findmyway** [rikhuijzer/Books.jl#60]
Let's say I want to work on a little book which supports two languages (en_us, zh_cn). I can create two configs but it seems they share the same index.md, right? How about making it configurable?

**Comment by rikhuijzer** [comment]
Are you using different projects to distinguish the languages? That is a nice use of that feature. 

I think the most neat solution would then be to add a `index_file` setting to `config.toml`. Would that work for you? That's a reasonably easy addition. Let me know whether that works for you and I'll get it into the package in a week.

**Comment by rikhuijzer** [comment]
I just realized that you still would need a landing page of some sorts from which users can choose which language they want to see, right? Although you can change projects quite easily on `localhost`, I haven't really thought about how to show multiple projects at the static website, but I'm open for supporting that.

**Comment by findmyway** [comment]
> I just realized that you still would need a landing page of some sorts from which users can choose which language they want to see, right? 

Yeah, after thinking for a while. I agree that I still need a landing page here.

> I haven't really thought about how to show multiple projects at the static website

My current plan is to host different versions under different paths (mysite.com/en, mysite.com/cn). #49 may be needed.

Anyway, I think we can keep things as it is now. ❤️

**Comment by rikhuijzer** [comment]
More people want this: https://discourse.julialang.org/t/how-about-a-great-hand-note-type-of-a-static-site-for-julia/57177, so I'll reopen the issue.

**Comment by rikhuijzer** [comment]
@findmyway, can I add your project at <https://github.com/LearnJuliaTheFunWay/JuliaDevelopersToolkit> as an example for this issue? I'll add it to the documentation too then. It's a perfect example for a simple site which is built in two languages.

**Comment by findmyway** [comment]
Cool!

I'd prefer to add https://github.com/LearnJuliaTheFunWay/LearnJuliaTheFunWay.jl instead since I'll mainly work on it from now on. (Original code in JuliaDevelopersToolkit were moved into it)

**Comment by rikhuijzer** [comment]
Thanks!
