### ISSUE TITLE
How to insert an image?

### ISSUE THREAD

**Issue by findmyway** [rikhuijzer/Books.jl#94]
Well, from the doc I can only know how to generate a figure in Julia and insert it into the book. But how could I insert an existing image from a local file?

**Comment by rikhuijzer** [comment]
It’s nice to hear that you’re still using the package. Is it going well? Let me know if you need things for which you guess other people need it too, like for example Plots.jl support.

I’m not at my computer right now and will add some instructions tomorrow.

**Comment by findmyway** [comment]
> It’s nice to hear that you’re still using the package. Is it going well? Let me know if you need things for which you guess other people need it too, like for example Plots.jl support.

Yeah, I'm still working on it. At least for now, I'm quite satisfied with this package. You may see my progress here: https://github.com/LearnJuliaTheFunWay/JuliaDevelopersToolkit and preview the page here https://learnjuliathefunway.com/JuliaDevelopersToolkit/

The PDFs of both English and Chinese version are generated as expected.

> I’m not at my computer right now and will add some instructions tomorrow.

No hurry. 😃
